name: Terraform Destroy
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${(secrets.AWS_ACCESS_KEY_ID)}
  AWS_SECRET_KEY: ${(secrets.AWS_SECRET_KEY)}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}


  jobs:
    terrafoem:
      name: terraform
      runs-on: ubuntu-lastest
      defaults:
        run:
          shell: bash
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform destroy -auto-approve